import { readFile, writeFile, mkdir, rm, cp } from "node:fs/promises";
import { dirname, join } from "node:path";

const root = new URL("../", import.meta.url).pathname;
const source = join(root, "source");
const dist = join(root, "dist");
const site = JSON.parse(await readFile(join(source, "data/site.json"), "utf8"));
const pages = JSON.parse(await readFile(join(source, "data/pages.json"), "utf8"));

const esc = (value="") => value.replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const url = path => `${site.domain}${path === "/" ? "/" : path}`;
const nav = `<nav aria-label="Primary navigation"><a href="/solutions/">Solutions</a><a href="/projects/">Projects</a><a href="/insights/">Insights</a><a href="/health-check/">Health Check</a><a href="/contact/">Contact</a></nav>`;

function analytics(){
  const ga = site.googleAnalyticsId ? `<script async src="https://www.googletagmanager.com/gtag/js?id=${esc(site.googleAnalyticsId)}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${esc(site.googleAnalyticsId)}');</script>` : "<!-- Add googleAnalyticsId in source/data/site.json -->";
  const clarity = site.microsoftClarityId ? `<script>(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src='https://www.clarity.ms/tag/'+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y)})(window,document,'clarity','script','${esc(site.microsoftClarityId)}');</script>` : "<!-- Add microsoftClarityId in source/data/site.json -->";
  return `<!-- ANALYTICS: START -->${ga}${clarity}<!-- ANALYTICS: END -->`;
}

function head(page){
 const schema={"@context":"https://schema.org","@type":page.page==="home"?"ProfessionalService":"WebPage","name":page.title,"url":url(page.path),"description":page.description,...(page.page==="home"?{"telephone":site.phoneDisplay,"email":site.email,"areaServed":["Tamil Nadu","India","Online"],"founder":{"@type":"Person","name":"Dr Krishna Teja Perannagari","url":site.linkedin}}:{})};
 return `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(page.title)} | ${esc(site.siteName)}</title><meta name="description" content="${esc(page.description)}"><link rel="canonical" href="${url(page.path)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${url(page.path)}"><meta property="og:site_name" content="${esc(site.siteName)}"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#102d35">${site.googleSiteVerification?`<meta name="google-site-verification" content="${esc(site.googleSiteVerification)}">`:""}${site.bingSiteVerification?`<meta name="msvalidate.01" content="${esc(site.bingSiteVerification)}">`:""}<script type="application/ld+json">${JSON.stringify(schema).replaceAll("<","\\u003c")}</script>${analytics()}<link rel="stylesheet" href="/assets/css/styles.css"><script src="/assets/js/site.js" defer></script></head>`;
}

function shell(page, content, extra=""){
 return `<!doctype html><html lang="en">${head(page)}<body><a class="skip" href="#main">Skip to content</a><header><div class="wrap nav"><a class="brand" href="/"><span class="mark">KT</span><span><b>${site.siteName}</b><small>${site.descriptor}</small></span></a>${nav}<a class="nav-cta" href="/contact/">Discuss a challenge</a></div></header><main id="main">${content}</main><footer><div class="wrap footer-grid"><div><div class="brand"><span class="mark">KT</span><span><b>${site.siteName}</b><small>Practical marketing solutions</small></span></div><p>Independent professional platform connecting marketing insight, analytical thinking and practical business application.</p></div><div><b>Explore</b><a href="/solutions/">Solutions</a><a href="/projects/">Projects</a><a data-event="blog_click" href="${site.blog}" target="_blank" rel="noopener noreferrer">Marketing & Beyond blog</a><a data-event="linkedin_click" href="${site.linkedin}" target="_blank" rel="noopener noreferrer">LinkedIn profile</a></div><div><b>Contact</b><a data-event="phone_click" href="tel:${site.phoneHref}">${site.phoneDisplay}</a><a data-event="email_click" href="mailto:${site.email}">${site.email}</a><span>${site.location}</span></div></div><div class="wrap footer-bottom"><span>© ${new Date().getUTCFullYear()} ${site.siteName}</span><a href="/privacy/">Privacy</a></div></footer>${extra}</body></html>`;
}

const hero=(kicker,title,text)=>`<section class="page-hero"><div class="wrap"><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${text}</p></div></section>`;
const cta=`<section class="cta"><div class="wrap"><div><p class="eyebrow orange">LET'S BEGIN WITH THE PROBLEM</p><h2>What is holding your marketing back?</h2></div><a class="button light" href="/contact/">Discuss your requirement →</a></div></section>`;
const services=[
 ["Marketing Strategy","Clarify your market, customer segments, positioning and priorities."],["Digital Growth","Strengthen your website, content, search visibility and customer journey."],["Customer Experience & CRM","Improve acquisition, service, retention and customer relationships."],["Marketing Analytics","Turn customer and performance data into actionable decisions."],["AI-Enabled Marketing","Adopt practical AI workflows with clear safeguards and business purpose."],["Workshops & Capability","Build practical marketing capability among managers, teams and entrepreneurs."]];

function content(name){
 if(name==="home")return `<section class="hero wrap"><div><p class="eyebrow">MARKETING CONSULTANT · TAMIL NADU & ONLINE</p><h1>Turn marketing challenges into <em>growth opportunities.</em></h1><p class="lede">Practical, data-driven marketing solutions for SMEs, start-ups and growing organisations—from customer clarity to digital performance and applied AI.</p><div class="actions"><a class="button primary" href="/solutions/">Explore solutions →</a><a class="button ghost" href="/health-check/">Take the health check</a></div></div><div class="hero-panel">${[["01","Discover","Business, customers, context"],["02","Diagnose","Gaps, evidence, opportunities"],["03","Design","Strategy and priorities"],["04","Enable","Tools, workshops, review"]].map(x=>`<div class="signal"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join("")}</div></section><section class="section wrap"><div class="section-head"><p class="eyebrow">WHAT I HELP SOLVE</p><h2>Marketing clarity that moves work forward.</h2><p>Choose a specific business challenge or begin with a comprehensive marketing review.</p></div><div class="card-grid">${services.map((s,i)=>`<a class="solution-card" href="/solutions/#service-${i+1}"><span>0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p><b>View solution →</b></a>`).join("")}</div></section>${cta}`;
 if(name==="solutions")return `${hero("CONSULTANCY SOLUTIONS","Built around your business question.","Every engagement begins with the decision you need to make—not a predetermined tool or template.")}<section class="section wrap service-list">${services.map((s,i)=>`<article id="service-${i+1}" class="service-row"><div><span class="number">0${i+1}</span><h2>${s[0]}</h2><p>${s[1]}</p></div><div><b>THE WORK CAN INCLUDE</b><ul>${([ ["Market and competitor assessment","Customer segmentation","Value proposition development","Marketing roadmap"],["Website and digital-presence review","SEO and content direction","Customer-journey assessment","Campaign review"],["Customer-journey mapping","CRM strategy","Experience-gap diagnosis","Retention planning"],["Measurement framework","Customer and sales-data analysis","Dashboards","Decision support"],["AI-readiness assessment","Prompt and workflow design","AI-assisted research","Responsible-use guidance"],["Marketing for SME growth","Digital marketing with applied AI","Customer experience","Analytics for managers"]][i]).map(x=>`<li>${x}</li>`).join("")}</ul><a data-event="service_enquiry_click" href="/contact/?service=${encodeURIComponent(s[0])}">Discuss this solution →</a></div></article>`).join("")}</section>${cta}`;
 if(name==="projects"){const p=[["Market research","Township development","Customer research, market assessment and value-proposition evaluation."],["B2B strategy","Cybersecurity business","Customer-segment prioritisation and positioning in a competitive technology market."],["Channel growth","Partner performance","Assessment of channel-partner performance and revenue-growth opportunities."],["Customer experience","Service support","Identification of service gaps and opportunities to strengthen customer satisfaction."],["E-commerce analytics","Product returns","Analysis of return patterns and customer evidence to identify business responses."],["Community strategy","Digital co-creation","Design of customer participation and co-creation mechanisms."],["Market entry","Fashion e-commerce","Assessment of customer expectations, competition and growth options."],["Technology adoption","Enterprise CRM","Conditions influencing CRM solution success in an enterprise ecosystem."]];return `${hero("BUSINESS APPLICATIONS","Evidence applied to real decisions.","Selected examples of business research, supervised projects and applied problem-solving.")}<section class="section wrap"><div class="project-grid">${p.map((x,i)=>`<article><span>0${i+1} · ${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join("")}</div><p class="note">These examples demonstrate areas of business research and problem-solving experience. Certain projects were undertaken as teaching cases, supervised studies or applied research engagements.</p><section class="profile"><div><p class="eyebrow">ABOUT THE CONSULTANT</p><h2>Dr Krishna Teja Perannagari</h2><a class="button primary" href="${site.linkedin}" target="_blank" rel="noopener noreferrer">View LinkedIn profile</a></div><p>A marketing educator, researcher and business advisor whose work spans strategy, customer experience, CRM, analytics, digital marketing and applied AI. Marketing expertise, software experience and data analysis support a practical, evidence-led approach.</p></section></section>${cta}`}
 if(name==="insights")return `${hero("INSIGHTS","Ideas made useful for practice.","Practical writing on customers, brands, digital growth, measurement and AI in marketing.")}<section class="section wrap"><div class="topics">${["Marketing fundamentals","Branding & consumer behaviour","Digital marketing","AI & marketing","SEO & generative search","Marketing analytics","SME marketing"].map(x=>`<span>${x}</span>`).join("")}</div><section class="featured"><div><p class="eyebrow">MARKETING & BEYOND BLOG</p><h2>A knowledge base for business owners, professionals and learners.</h2><p>Explore writing on small-business digital marketing, brand identity, consumer behaviour, search, analytics and AI-enabled marketing.</p><a class="button primary" href="${site.blog}" target="_blank" rel="noopener noreferrer">Visit the complete blog ↗</a></div><div class="art"><span>Customer</span><span>Evidence</span><span>Technology</span><b>BETTER<br>MARKETING<br>DECISIONS</b></div></section></section>`;
 if(name==="health")return `${hero("INTERACTIVE ASSESSMENT","How healthy is your marketing system?","Rate ten practical capabilities and receive an instant score with next steps.")}<section class="section wrap"><div class="quiz"><div id="health-questions" class="quiz-card"></div><aside class="score"><p>YOUR SCORE</p><strong id="health-score">—<small>/100</small></strong><h2 id="health-title">Complete the assessment</h2><p id="health-advice">Rate each statement, then calculate your capability score.</p><a class="button light" href="/contact/">Discuss the result</a></aside></div></section>`;
 if(name==="contact")return `${hero("START A CONVERSATION","Tell me the decision you need to make.","Share a brief description of your marketing challenge and prepare a structured enquiry.")}<section class="section wrap contact"><div class="contact-info"><h2>Contact</h2><a href="tel:${site.phoneHref}">${site.phoneDisplay}</a><a href="mailto:${site.email}">${site.email}</a><p>${site.location}</p><p>Available Monday–Friday · Online and customised engagements</p></div><form id="enquiry" class="form"><div class="field-row"><label>Name<input required name="name" autocomplete="name"></label><label>Organisation<input name="organisation" autocomplete="organization"></label></div><div class="field-row"><label>Email<input required type="email" name="email" autocomplete="email"></label><label>Phone<input name="phone" autocomplete="tel"></label></div><label>Primary requirement<select required name="service"><option value="">Select a solution</option>${services.map(x=>`<option>${x[0]}</option>`).join("")}</select></label><label>Preferred consultation mode<select required name="mode"><option value="">Select a mode</option><option>Online</option><option>Onsite</option><option>Hybrid</option><option>Open to Discussion</option></select></label><label>Business decision or challenge<textarea required name="challenge" rows="5"></textarea></label><label class="consent"><input type="checkbox" required> I agree to prepare an email containing these details.</label><div class="form-actions"><button class="button primary" type="submit">Continue in Gmail</button><button class="button ghost" id="email-app" type="button">Open Email App</button><button class="button ghost" id="copy-details" type="button">Copy Details</button></div><p id="form-notice" class="form-notice" hidden></p><p class="form-note">The website does not store your information. Review the prepared message before sending it.</p></form></section>`;
 return `${hero("PRIVACY","Clear and transparent communication.","How this website handles enquiries, analytics and external links.")}<section class="section wrap prose"><h2>Enquiries</h2><p>The enquiry form prepares an email in the visitor's email application. The website does not store or transmit form information directly.</p><h2>Analytics</h2><p>When analytics identifiers are configured, the website may measure aggregate visits and interactions through Google Analytics and Microsoft Clarity. This notice should be reviewed before activating tracking.</p><h2>External links</h2><p>Links to LinkedIn, Gmail and the external blog are governed by those services' own privacy practices.</p></section>`;
}

await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});
await cp(join(source,"assets"),join(dist,"assets"),{recursive:true});
for(const page of pages){const target=join(dist,page.file);await mkdir(dirname(target),{recursive:true});const extra=page.page==="health"?'<script src="/assets/js/health-check.js" defer></script>':page.page==="contact"?`<script>window.SITE_EMAIL=${JSON.stringify(site.email)}</script><script src="/assets/js/contact.js" defer></script>`:"";await writeFile(target,shell(page,content(page.page),extra));}
await writeFile(join(dist,"CNAME"),"krishnateja.perannagari.com\n");
await writeFile(join(dist,".nojekyll"),"");
await writeFile(join(dist,"robots.txt"),`User-agent: *\nAllow: /\nSitemap: ${site.domain}/sitemap.xml\n`);
await writeFile(join(dist,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${url(p.path)}</loc></url>`).join("")}</urlset>`);
await writeFile(join(dist,"404.html"),shell({title:"Page Not Found",description:"The requested page could not be found.",path:"/404.html",page:"404"},`<section class="page-hero"><div class="wrap"><p class="eyebrow">404</p><h1>Page not found.</h1><p>The requested page may have moved. <a href="/">Return to the homepage.</a></p></div></section>`));
console.log(`Built ${pages.length} pages in dist/`);
